[build]
  publish = "dist"
  command = "npm ci && node build-static.js"
  
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true
  
[build.processing.js]
  bundle = true
  minify = true
  
[build.processing.html]
  pretty_urls = false

[[redirects]]
  from = "/ads.txt"
  to = "https://srv.adstxtmanager.com/19390/dunk-calculator.info"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"